BankLoanSystem/BankLoanSystem/Models/ForgotPassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Web;

namespace BankLoanSystem.Models
{
    public class ResetPassword
    {
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Password is required")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }


    }

    public class ForgotPassword
    {

        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        public string token { get; set; }

        /// <summary>
        /// Generates random strings with a given length
        /// </summary>
        /// <param name="size">Size of the string</param>
        /// <param name="lowerCase">If true, generate lowercase string</param>
        /// <returns>Random string</returns>
        public string GenerateRandomString(int size)
        {
            StringBuilder builder = new StringBuilder();
            Random random = new Random();
            char ch;
            for (int i = 1; i < size + 1; i++)
            {
                ch = Convert.ToChar(Convert.ToInt32(Math.Floor(26 * random.NextDouble() + 65)));
                builder.Append(ch);
            }

            token = builder.ToString();


            return token;
        }
    }
}

BankLoanSystem/BankLoanSystem/Controllers/ManageUser/ForgotPasswordController.cs
using BankLoanSystem.DAL;
using BankLoanSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankLoanSystem.Controllers.ManageUser
{
    public class ForgotPasswordController : Controller
    {
        // GET: ForgotPassword

        /// <summary>
        /// CreatedBy : MAM. IRFAN
        /// CreatedDate: 2016/01/13
        /// 
        /// Showing Enter email page
        /// 
        /// </summary>
        /// <returns></returns>
        /// 
        public ActionResult Index()
        {

            return View();
        }


        /// <summary>
        /// CreatedBy : MAM. IRFAN
        /// CreatedDate: 2016/01/17
        /// 
        /// Check the email, if it is correct generate a token and save it to database.
        /// And send email with token to client
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(ForgotPassword forgotPassword)
        {
            int userId = (new UserAccess()).getUserId(forgotPassword.Email);
            if (userId == 0)
            {
                ViewBag.ErrorMsg = "User Account not exists";
                return View();
            }

            string userName = (new UserAccess()).retreiveUserByUserId(userId).UserName;

            try
            {
                // generate token
                forgotPassword.token = forgotPassword.GenerateRandomString(30);





                // save it to db
                bool isUpdate = (new forgotPasswordTokenAccess()).updateToken(userId, forgotPassword.token);

                if (!isUpdate)
                {
                    ViewBag.ErrorMsg = "Updating Failed";
                    return View();
                }
                // sendit to the user

                Email email = new Email(forgotPassword.Email);


                int isSuccess = email.SendMail("Hi " + userName + " ! <br><br>We recieved a request to reset your password.<br><br> Click here to Reset Your password : <a href='http://localhost:57318/ForgotPassword/ConfirmAccount?userId=" + userId + "&token=" + forgotPassword.token + "'>Link</a><br> If you don't want to change your password, you can ignore this email.<br><br> Thanks,<br> The Futunet Net Team", "Account - Help (Reset Your Password)");
                if (isSuccess == 0)
                {
                    ViewBag.errorMsg = "Sending Mail Failed";
                    return View();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }


            ViewBag.Message = "Instructions on how to reset Your Password have been sent to your inbox";
            return View();
        }


        /// <summary>
        /// CreatedBy : MAM. IRFAN
        /// CreatedDate: 2016/01/17
        /// 
        /// Confirm the the user account using usedId and token
        /// 
        /// </summary>
        /// <returns></returns>

        public ActionResult ConfirmAccount(int userId, string token)
        {


            bool isSuccuss = (new forgotPasswordTokenAccess()).verifyAccount(userId, token);
            if (isSuccuss)
            {

                Session["forgotId"] = userId;
                return RedirectToAction("ResetPassword");
            }
            return new HttpStatusCodeResult(404);
        }

        // <summary>
        /// CreatedBy : MAM. IRFAN
        /// CreatedDate: 2016/01/17
        /// 
        /// Reset Password Page view
        /// 
        /// </summary>
        /// <returns></returns>

        public ActionResult ResetPassword(string message)
        {
            if (message != null)
            {
                ViewBag.message = message;
                Session.Abandon();
            }

            return View();
        }


        // <summary>
        /// CreatedBy : MAM. IRFAN
        /// CreatedDate: 2016/01/17
        /// 
        /// Reset Password Page view
        /// 
        /// </summary>
        /// <returns></returns>

        [HttpPost]
        public ActionResult ResetPassword(ResetPassword resetPasswordModel)
        {

            // check the session, is exists allow otherwise don't
            int userId;
            try
            {
                userId = int.Parse(Session["forgotId"].ToString());
            }
            catch (Exception)
            {
                return new HttpStatusCodeResult(404);
            }


            bool isSuccess = (new forgotPasswordTokenAccess()).resetPassword(userId, resetPasswordModel);

            if (!isSuccess)
            {
                return new HttpStatusCodeResult(404);
            }

            ViewBag.message = "Your Password Sucessfully Updated";

            return RedirectToAction("ResetPassword", new { message = ViewBag.message });
        }


    }
}

BankLoanSystem/BankLoanSystem/Views/ForgotPassword/Index.cshtml
@model BankLoanSystem.Models.ForgotPassword

@{
    ViewBag.Title = "Forgot Password";
    Layout = "~/Views/Shared/_login.cshtml";

}

@if (ViewBag.Message != null)
{

    @Html.AntiForgeryToken()


    <h3>Email has been Sent!</h3>

        <p>@ViewBag.Message </p>
        <br>
        <p> If you didn't receive mail click below and resend the mail </p>

        <small> @Html.ActionLink("Back to Send Email", "Index")</small>


}

@if (ViewBag.Message == null)
{


    <h3>Account Help</h3>
    <p>
        <!--Continually expanded and constantly improved Inspinia Admin Them (IN+)-->
    </p>
    <p>Enter the email address you used to create the account and we will send you instructions</p>

    using (Html.BeginForm("Index", "ForgotPassword", FormMethod.Post, new { @class = "m-t" }))
    {
        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label id="successLabel">@ViewBag.SuccessMsg</label>
            <label id="errorLabel">@ViewBag.ErrorMsg</label>

            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Email" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

        </div>
            <button type="submit" class="btn btn-primary block full-width m-b">Send</button>


    }


    @Html.ActionLink("Back to Login", "UserLogin", "Login")

}



<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

BankLoanSystem/BankLoanSystem/Views/ForgotPassword/ResetPassword.cshtml
@model BankLoanSystem.Models.ResetPassword

@{
    ViewBag.Title = "Reset Password";
    Layout = "~/Views/Shared/_login.cshtml";
}

@if (ViewBag.message == null)
{
    <h3>Reset Password</h3>

    using (Html.BeginForm("ResetPassword", "ForgotPassword", FormMethod.Post, new { @class = "m-t" }))
    {
        @Html.AntiForgeryToken()



        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", placeholder = "Password" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

        </div>

        <div class="form-group">


            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", placeholder = "Confirm Password" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })

        </div>


        <button type="submit" class="btn btn-primary block full-width m-b">Reset Password</button>


    }
}

@if (ViewBag.message != null)
{
    <h3>Your Password Successfully Updated!</h3>

    <p>Click the Link below to Login </p>

    @Html.ActionLink("Back to Login", "UserLogin", "Login")

}