BankLoanSystem/BankLoanSystem/Controllers/CreateUser/CreateUserController.cs
using System;
using System.Collections.Generic;
using System.Runtime.Remoting.Messaging;
using System.Web.Mvc;
using BankLoanSystem.DAL;
using BankLoanSystem.Models;
using BankLoanSystem.Code;
using System.Text;

namespace BankLoanSystem.Controllers.CreateUser
{
    public class CreateUserController : Controller
    {
        private static int _createById;
        private static int _companyId;
        private static int _curUserRoleId;
        private static int _curBranchId;

        /// <summary>
        /// CreatedBy : Kanishka SHM
        /// CreatedDate: 2016/01/16
        /// 
        /// Inserting user details
        /// 
        /// argument: None
        /// 
        /// </summary>
        /// <returns>Return view</returns>

        // GET: CreateUser
        public ActionResult Create(string lbls)
        {
            
            int.Parse(Session["userId"].ToString());

            if (lbls != null)
            {
                ViewBag.SuccessMsg = "User Successfully Created";
            }
            //int id = (int)Session["userId"];
            int id = Convert.ToInt32(Session["userId"].ToString());
            UserAccess ua = new UserAccess();
            User curUser = ua.retreiveUserByUserId(id);
            ViewBag.CurrUserRoleType = curUser.RoleId;

            //Restrict to create above user role 
            RoleAccess ra = new RoleAccess();
            List<UserRole> roleList = ra.GetAllUserRoles();
            List<UserRole> tempRoleList = new List<UserRole>();

            //if current user is first super admin he can create aditional super admin
            if (curUser.UserId == curUser.CreatedBy)
            {
                //ViewBag.RoleId = new SelectList(roleList, "RoleId", "RoleName");
                tempRoleList = roleList;
            }
            else
            {
                for (int i = 1; i < roleList.Count && ViewBag.CurrUserRoleType != 3; i++)
                {
                    UserRole tempRole = new UserRole()
                    {
                        RoleId = roleList[i].RoleId,
                        RoleName = roleList[i].RoleName
                    };
                    tempRoleList.Add(tempRole);
                }
            }
            _createById = curUser.UserId;
            _companyId = curUser.Company_Id;
            _curUserRoleId = curUser.RoleId;
            ViewBag.RoleId = new SelectList(tempRoleList, "RoleId", "RoleName");
            _curBranchId = curUser.BranchId;

            // get all branches
            List<Branch> branchesLists = (new BranchAccess()).getBranches(curUser.Company_Id);

            //if current user is admin restrict to creat user for another branch
            if (ViewBag.CurrUserRoleType == 2)
            {
                //ViewBag.BranchId = new SelectList(branchesLists, "BranchId", "BranchName", curUser.BranchId);
                _curBranchId = curUser.BranchId;
            }
            else
            {
                ViewBag.BranchId = new SelectList(branchesLists, "BranchId", "BranchName");
            }

            return PartialView("Create"); 
        }

        /// <summary>
        /// CreatedBy : Kanishka SHM
        /// CreatedDate: 2016/01/16
        /// 
        /// Inserting user details
        /// 
        /// argument: User
        /// 
        /// </summary>
        /// <returns>Data Successfully inserted! / Failed to insert!</returns>
        [HttpPost]
        public ActionResult Create(User user)
        {

            
            int.Parse(Session["userId"].ToString());


            user.CreatedBy = _createById;
            user.IsDelete = false;
            user.Status = false;

            //Set admin branch to new user 
            if (_curUserRoleId == 2)
            {
                user.BranchId = _curBranchId;
            }

            //Check role is selected
            if (user.RoleId == 0)
                user.RoleId = 2;

            //Check branch is selected
            if (_curUserRoleId == 1 && user.BranchId == 0)
            {
                user.BranchId = _curBranchId;
            }
            string passwordTemp = user.Password;

            UserAccess ua = new UserAccess();

            string newSalt = PasswordEncryption.RandomString();
            user.Password = PasswordEncryption.encryptPassword(user.Password, newSalt);
            user.Email = user.NewEmail;

            //Insert user
            int res = ua.InsertUser(user);

            //Insert new user to user activation table
            string activationCode = Guid.NewGuid().ToString();
            int userId = (new UserAccess()).getUserId(user.Email);
            res = ua.InsertUserActivation(userId, activationCode);
            if (res == 1)
            {
                ViewBag.SuccessMsg = "Data Successfully inserted!";
                
                string body = "Hi " + user.FirstName + "! <br /><br /> Your account has been successfully created. Below in your account detail." +
                              "<br /><br /> User name: " + user.UserName +
                                    "<br /> Password : <b>" + passwordTemp +
                              "<br />Click <a href='http://localhost:57318/CreateUser/ConfirmAccount?userId=" + userId + "&activationCode=" + activationCode + "'>here</a> to activate your account." +
                              "<br /><br/> Thanks,<br /> Admin.";

                Email email = new Email(user.Email);
                email.SendMail(body, "Account details");

                
                // check the user as superadmin or admin..
                if (user.RoleId == 1 || user.RoleId == 2)
                {
                    ViewBag.SuccessMsg = "User Successfully Created";
                    

                   
                    return RedirectToAction("create",new { lbls = ViewBag.SuccessMsg });
                }

                Session["editUserIds"] = userId;


                return RedirectToAction("SetRights", "EditRights", new {@lbl1 = ViewBag.SuccessMsg });
            }
            else
            {
                ViewBag.ErrorMsg = "Failed to create user!";

                //Restrict to create above user role 
                RoleAccess ra = new RoleAccess();
                List<UserRole> roleList = ra.GetAllUserRoles();
                List<UserRole> tempRoleList = new List<UserRole>();

                for (int i = roleList[_curUserRoleId - 1].RoleId; i <= roleList.Count && _curUserRoleId != 3; i++)
                {
                    UserRole tempRole = new UserRole()
                    {
                        RoleId = roleList[i - 1].RoleId,
                        RoleName = roleList[i - 1].RoleName
                    };
                    tempRoleList.Add(tempRole);
                }

                ViewBag.RoleId = new SelectList(tempRoleList, "RoleId", "RoleName");

                // get all branches
                List<Branch> branchesLists = (new BranchAccess()).getBranches(_companyId);
                ViewBag.BranchId = new SelectList(branchesLists, "BranchId", "BranchName");


                return PartialView("Create");
            }
        }

        /// <summary>
        /// CreatedBy : Kanishka SHM
        /// CreatedDate: 2016/01/16
        /// 
        /// Check weather user name already exist
        /// 
        /// argument: userName(string)
        /// 
        /// </summary>
        /// <returns>Return JsonResult</returns>
        public JsonResult IsUserNameExists(string userName)
        {
            //check user name is already exist.  
            return Json((new UserAccess()).IsUniqueUserName(userName), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// CreatedBy : Kanishka SHM
        /// CreatedDate: 2016/01/16
        /// 
        /// Check weather user name already exist
        /// 
        /// argument: userName(string)
        /// 
        /// </summary>
        /// <returns>Return JsonResult</returns>
        public JsonResult IsEmailExists(string newEmail)
        {
            //check user name is already exist.  
            return Json((new UserAccess()).IsUniqueEmail(newEmail), JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// CreatedBy : Kanishka SHM
        /// CreatedDate: 2016/01/17
        /// EditedDate:2016/01/19
        /// Create first super admin view
        /// 
        /// argument: None
        /// 
        /// </summary>
        /// <returns>Return to view create first super admin</returns>
        [HttpGet]
        public ActionResult CreateFirstSuperUser()
        {
            if (Session["type"] == null)
                return RedirectToAction("UserLogin", "Login");

            return View();
        }

        /// <summary>
        /// CreatedBy :  Kanishka SHM
        /// CreatedDate: 2016/01/18
        /// EditedDate:  2016/01/19
        /// Create first super admin
        /// 
        /// argument: user(User)
        /// 
        /// </summary>
        /// <returns>Return to view create first super admin</returns>
        [HttpPost]
        public ActionResult CreateFirstSuperUser(User user)
        {
            //user.Password = PasswordEncryption.encryptPassword(user.Password);

            string newSalt = PasswordEncryption.RandomString();
            user.Password = PasswordEncryption.encryptPassword(user.Password, newSalt);
            user.Email = user.NewEmail;
            TempData["User"] = user;
            return RedirectToAction("Setup", "SetupCompany", new { id = 0, type = "CompanyEmployee" });
        }

        ///// <summary>
        ///// CreatedBy :  Kanishka SHM
        ///// CreatedDate: 2016/01/19
        ///// activated account
        /// 
        /// <param name="userId"></param>
        /// <param name="activationCode"></param>
        /// <returns>Return to view create first super admin</returns>

BankLoanSystem/BankLoanSystem/Views/CreateUser/ConfirmAccount.cshtml
@{
    ViewBag.Title = "ConfirmAccount";
    Layout = "~/Views/Shared/_login.cshtml";
}

@if (@ViewBag.IsError != 1)
{
    <h2>Account activation mail.</h2>

    <p>Your account has been activated</p>
    <br/>
    <text>Click &nbsp;    </text>
    @Html.ActionLink("Here", "UserLogin", "Login")
    <text> &nbsp; to login.    </text>
}

BankLoanSystem/BankLoanSystem/Views/CreateUser/Create.cshtml
@model BankLoanSystem.Models.User

@{
    ViewBag.Title = "Create User";
}

<h2>Create User</h2>



@using (Ajax.BeginForm("Create","CreateUser", new AjaxOptions()
{
    
    OnFailure = "handleError",
    HttpMethod = "POST",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "changeContainer",
    LoadingElementId = "loadingDiv"
}, new {id = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <label id="successLabel">@ViewBag.SuccessMsg</label>
        <div class="form-group">
            <div class = "control-label col-sm-2">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-xs-8"> 
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-sm-2">
                @Html.LabelFor(model => model.Password, htmlAttributes: new {})<span style="color: red">*</span>
            </div>

            <div class="col-xs-8">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-sm-2">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { })<span style="color:red">*</span>
            </div>

            <div class="col-xs-8">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
           
            <div class="col-xs-8">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-xs-8">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2">
                @Html.LabelFor(model => model.NewEmail, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
           
            <div class="col-xs-8">
                @Html.EditorFor(model => model.NewEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2" >
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-xs-8">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (ViewBag.CurrUserRoleType != 2)
        {
            <div class="form-group">
                <div class = "control-label col-sm-2">
                    @Html.LabelFor(model => model.BranchId, htmlAttributes: new { })<span style="color:red">*</span>
                </div>
               
                <div class="col-xs-8">
                    @Html.DropDownListFor(model => model.BranchId, null, "Select branch", htmlAttributes: new { @class = "form-control", id = "BranchId" })
                    @Html.ValidationMessageFor(model => model.BranchId, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            <div class = "control-label col-sm-2" >
                @Html.LabelFor(model => model.RoleId, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-xs-8">
                @Html.DropDownListFor(model => model.RoleId, null, "Select role", htmlAttributes: new { @class = "form-control", id = "RoleId" })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger", @id = "RoleIdValidate" })
            </div>
        </div>

        <div class="form-group">
            <div>

                <nav>
                    <ul class="pager">
                        <li>
                            <input type="submit" value="Create" class="btn btn-primary m-b" style="float:left" />
                        </li>

                        <li>
                            <input id="clear" type="button" value="Clear" class="btn btn-primary m-b" style="float:left;margin-left:10px"  />
                            
                        </li>
                        </ul>
</nav>
            </div>
        </div>
    </div>
    
}

<div>
    
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

<script>


    $('#clear').click(function () {
        document.getElementById("form").reset();
    });


</script>

BankLoanSystem/BankLoanSystem/Views/CreateUser/CreateFirstSuperUser.cshtml
@model BankLoanSystem.Models.User

@{
    ViewBag.Title = "CreateFirstSuperUser";
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
}

<h2>Super Admin Details</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class = "control-label col-sm-2" >
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-sm-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2" >
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-sm-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2" >
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-sm-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2" >
                @Html.LabelFor(model => model.NewEmail, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-sm-10">
                @Html.EditorFor(model => model.NewEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NewEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2" >
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
           
            <div class="col-sm-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-sm-2">
                @Html.LabelFor(model => model.Password, htmlAttributes: new {})<span style="color: red">*</span>
            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.Password, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Password, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-sm-2">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { })<span style="color: red">*</span>
            </div>

            <div class="col-sm-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-sm-2">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { })<span style="color:red">*</span>
            </div>
            
            <div class="col-sm-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div>
                <nav>
                    <ul class="pager">
                        <li><input type="submit" value="Next" class="btn btn-primary m-b" style="float:left" /></li>
                        <li><input type="button" value="Clear" class="btn btn-primary m-b" style="float:left;margin-left:10px" onclick="location.href='@Url.Action("CreateFirstSuperUser", "CreateUser")'" /></li>
                    </ul>
                </nav>
                
                
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>